services:
  postgres:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: mostest
      POSTGRES_DB: mattermost_test
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mmuser", "-d", "mattermost_test"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mm-dev

  mattermost:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8065:8065"
      - "8067:8067"
      - "8074:8074"
      - "8075:8075"
      - "8443:8443/udp"
    environment:
      TZ: "America/New_York"
      NODE_TZ: "America/New_York"
      MM_SERVICESETTINGS_DEFAULTTIMEZONE: "America/New_York"
      MM_TIMEZONE: "America/New_York"
      MM_LOCALIZATION_DEFAULTTIMEZONE: "America/New_York"
      MM_USERNAME: mmuser
      MM_PASSWORD: mostest
      MM_DBNAME: mattermost_test
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: "postgres://mmuser:mostest@postgres:5432/mattermost_test?sslmode=disable"
      MM_SERVICESETTINGS_SITEURL: "http://localhost:8065"
      MM_SERVICESETTINGS_LISTENADDRESS: ":8065"
      MM_SERVICESETTINGS_ENABLEDEVELOPER: "true"
      MM_SERVICESETTINGS_ENABLETESTING: "true"
      MM_SERVICESETTINGS_ENABLEIPV6: "false"
      MM_SERVICESETTINGS_ENABLEREMINDERS: "true"
      MM_SERVICESETTINGS_ALLOWEDUNTRUSTEDINTERNALCONNECTIONS: "*"
      MM_PLUGINSETTINGS_ENABLED: "true"
      MM_PLUGINSETTINGS_ENABLEUPLOADS: "true"
      MM_PLUGINSETTINGS_DIRECTORY: /mattermost/plugins
      MM_PLUGINSETTINGS_CLIENTDIRECTORY: /mattermost/client/plugins
      MM_PLUGINSETTINGS_AUTOMATICPREPACKAGEDPLUGINS: "true"
      MM_PLUGINSETTINGS_ENABLEMARKETPLACE: "true"
      MM_PLUGINSETTINGS_INSTALLEDPLUGINSTATE_FOCALBOARD: "true"
      MM_PLUGINSETTINGS_PREPACKAGEDPLUGINS_FOCALBOARD: "true"
      MM_PLUGINSETTINGS_INSTALLEDPLUGINSTATE_COM_GITHUB_SCOTTLEEDAVIS_MATTERMOST_PLUGIN_REMIND: "true"
      MM_PLUGINSETTINGS_PLUGINS_COM_GITHUB_SCOTTLEEDAVIS_MATTERMOST_PLUGIN_REMIND_TIMEZONE: "America/New_York"
      MM_PLUGINSETTINGS_PLUGINS_COM_GITHUB_SCOTTLEEDAVIS_MATTERMOST_PLUGIN_REMIND_DEFAULTTIMEZONE: "America/New_York"
      MM_PLUGINSETTINGS_PLUGINS_COM_GITHUB_SCOTTLEEDAVIS_MATTERMOST_PLUGIN_REMIND_FORCELOCALTIME: "true"
      MM_PLUGINSETTINGS_PLUGINS_COM_GITHUB_SCOTTLEEDAVIS_MATTERMOST_PLUGIN_REMIND_LOCATION: "America/New_York"
      MM_PLUGINSETTINGS_PLUGINS_COM_GITHUB_SCOTTLEEDAVIS_MATTERMOST_PLUGIN_REMIND_TIMEFORMAT: "12"
      MM_PLUGINSETTINGS_PLUGINS_COM_GITHUB_SCOTTLEEDAVIS_MATTERMOST_PLUGIN_REMIND_USESYSTEMTIMEZONE: "true"
      MM_FEATUREFLAGS_BOARDSREMINDER: "true"
      MM_FEATUREFLAGS_BOARDSUNFURL: "true"
      MM_FEATUREFLAGS_ENABLEBOARDS: "true"
      MM_LOGSETTINGS_CONSOLELEVEL: "DEBUG"
      MM_FILESETTINGS_ARCHIVERECURSION: "false"
      MM_FILESETTINGS_DIRECTORY: "/mattermost/data"
      MM_FILESETTINGS_ENABLEFILESEARCH: "true"
      MM_FILESETTINGS_MAXFILESIZE: "104857600"
      MM_FILESETTINGS_MAXMEMORYCACHE: "10485760"
      MM_BLEVESETTINGS_INDEXDIR: "/mattermost/bleve-indexes"
      MM_BLEVESETTINGS_ENABLEINDEXING: "true"
      MM_BLEVESETTINGS_ENABLESEARCHING: "true"
      MM_BLEVESETTINGS_ENABLEAUTOCOMPLETE: "true"
    volumes:
      - ./data/config:/mattermost/config
      - ./data/data:/mattermost/data
      - ./data/logs:/mattermost/logs
      - ./data/plugins:/mattermost/plugins
      - ./data/client-plugins:/mattermost/client/plugins
      - ./data/bleve-indexes:/mattermost/bleve-indexes
    networks:
      - mm-dev
    depends_on:
      postgres:
        condition: service_healthy

  odoo-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      TZ: "America/New_York"
      POSTGRES_DB: ${ODOO_DB_NAME}
      POSTGRES_USER: ${ODOO_DB_USER}
      POSTGRES_PASSWORD: ${ODOO_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/db/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${ODOO_DB_USER}", "-d", "${ODOO_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - odoo-network

  odoo-app:
    image: odoo:16.0
    restart: unless-stopped
    ports:
      - "8069:8069"
    environment:
      TZ: "America/New_York"
      ODOO_DB_NAME: ${ODOO_DB_NAME}
      ODOO_DB_USER: ${ODOO_DB_USER}
      ODOO_DB_PASSWORD: ${ODOO_DB_PASSWORD}
      ODOO_DB_HOST: odoo-db
      ODOO_DB_PORT: 5432
    command: odoo -c /etc/odoo/odoo.conf
    volumes:
      - ./volumes/odoo/addons:/mnt/extra-addons
      - ./volumes/odoo/config:/etc/odoo
      - ./volumes/odoo/data:/var/lib/odoo
    depends_on:
      odoo-db:
        condition: service_healthy
    networks:
      - odoo-network

  airflow-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5434:5432"
    volumes:
      - ./volumes/airflow-db:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    command: postgres -c 'password_encryption=md5' -c 'hba_file=/var/lib/postgresql/data/pg_hba.conf'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    networks:
      - airflow-network

  airflow-init:
    image: apache/airflow:2.7.1
    depends_on:
      airflow-db:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=your_secret_key_here
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=airflow
      - _AIRFLOW_WWW_USER_PASSWORD=airflow
      - _AIRFLOW_WWW_USER_FIRSTNAME=Admin
      - _AIRFLOW_WWW_USER_LASTNAME=User
      - _AIRFLOW_WWW_USER_EMAIL=admin@example.com
      - _AIRFLOW_WWW_USER_ROLE=Admin
      - PYTHONPATH=/opt/airflow
    user: "0:0"
    command: bash -c 'sleep 10 && airflow db init && airflow users create --username airflow --password airflow --firstname Admin --lastname User --role Admin --email admin@example.com'
    networks:
      - airflow-network

  airflow-webserver:
    image: apache/airflow:2.7.1
    depends_on:
      airflow-db:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=your_secret_key_here
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    volumes:
      - ./volumes/airflow/dags:/opt/airflow/dags
      - ./volumes/airflow/logs:/opt/airflow/logs
      - ./volumes/airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - airflow-network

  airflow-scheduler:
    image: apache/airflow:2.7.1
    depends_on:
      airflow-webserver:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    volumes:
      - ./volumes/airflow/dags:/opt/airflow/dags
      - ./volumes/airflow/logs:/opt/airflow/logs
      - ./volumes/airflow/plugins:/opt/airflow/plugins
    command: scheduler
    restart: unless-stopped
    networks:
      - airflow-network

  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=airflow-db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8npassword
      - DB_POSTGRESDB_SCHEMA=n8n
      - N8N_PORT=5678
      - NODE_ENV=production
      - TZ=America/New_York
      
    volumes:
      - ./volumes/n8n:/home/node/.n8n
    depends_on:
      airflow-db:
        condition: service_healthy
    networks:
      - airflow-network

networks:
  mm-dev:
    driver: bridge
  odoo-network:
    driver: bridge
  airflow-network:
    driver: bridge 